language: python
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull python:3.8-slim-buster
- chmod +x mvnw
script:
- docker build --tag python-docker .