language: python
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull python:3.8-slim-buster
script:
- docker build --tag airtiesitba/python-docker .
- docker push airtiesitba/python-docker